---

- name: Download Repository
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Package Key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  package:
    name: jenkins
    state: present

- name: Start Service
  service:
    name: jenkins
    state: started
  when: jenkins_service_start

- name: Enable Service
  service:
    name: jenkins
    enabled: "{{ jenkins_service_enable }}"

- name: Find Files
  shell: find / -name "jenkins.war"
  register: __jenkins_war
  changed_when: false

- debug: var=__jenkins_war
  changed_when: false
